function direct(url){try{const u=new URL(url);return u.protocol==="https:"?u.href:""}catch{return""}}
function embed(url){try{const u=new URL(url),h=u.hostname.toLowerCase();if(["youtube.com","www.youtube.com","www.youtube-nocookie.com"].includes(h)&&u.pathname.startsWith("/embed/"))return u.href;if(h==="player.vimeo.com"&&u.pathname.startsWith("/video/"))return u.href}catch{}return""}
function watchUrl(id,number){return `watch.html?id=${encodeURIComponent(id)}&ep=${number}`}
async function init(){
  const user=await userRequired();if(!user)return;
  document.querySelector("#header").innerHTML=header(user.email);
  const c=await catalog(),params=new URLSearchParams(location.search),a=c.anime.find(x=>x.id===params.get("id")),ep=a?.episodes.find(x=>x.number===Number(params.get("ep"))),root=document.querySelector("#content");
  if(!a||!ep){root.innerHTML='<section class="section"><h1>Episódio não encontrado</h1><a class="btn primary" href="catalog.html">Voltar ao catálogo</a></section>';return}
  const sorted=[...a.episodes].sort((x,y)=>x.number-y.number),index=sorted.findIndex(x=>x.number===ep.number),prev=sorted[index-1],next=sorted[index+1];
  let media="",note="";
  if(ep.sourceType==="direct"){
    const url=direct(ep.sourceUrl||"");
    media=url?`<video id="episodeVideo" controls playsinline preload="metadata" crossorigin="anonymous" aria-label="${esc(a.title+" — "+ep.title)}"><source src="${esc(url)}"><p>Seu navegador não consegue reproduzir este vídeo. Tente abrir em um navegador atualizado.</p></video>`:'<div class="placeholder"><div style="font-size:2.8rem">▶</div><h3>Vídeo ainda não configurado</h3><p>O player está pronto. Adicione em <code>catalog.json</code> uma URL HTTPS de um arquivo MP4/WebM que você tenha autorização para transmitir.</p></div>';
    note=url?"Se o vídeo não iniciar, confira se a URL é pública, usa HTTPS, aponta para um MP4/WebM e permite acesso pelo navegador.":"Este episódio ainda não tem um arquivo de vídeo autorizado associado.";
  }else{
    const url=embed(ep.sourceUrl||"");
    media=url?`<iframe src="${esc(url)}" title="${esc(a.title+" — "+ep.title)}" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; web-share" allowfullscreen loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>`:'<div class="placeholder"><h3>Incorporação oficial não configurada</h3><p>Use uma URL oficial de incorporação permitida do YouTube (/embed/) ou Vimeo (/video/). Não tente contornar bloqueios de incorporação.</p></div>';
    note="A reprodução incorporada respeita as limitações e os controles definidos pela plataforma de origem.";
  }
  root.innerHTML=`<section class="section watch-section"><a class="muted" href="anime.html?id=${encodeURIComponent(a.id)}">← Voltar para ${esc(a.title)}</a><p class="eyebrow">AGORA ASSISTINDO</p><h1>${esc(a.title)} — ${esc(ep.title)}</h1><p class="muted">Episódio ${ep.number} · ${esc(ep.duration||"Duração não informada")}</p><div class="video">${media}</div><p id="playerNote" class="muted player-note">${esc(note)}</p><div class="player-actions">${prev?`<a class="btn" href="${watchUrl(a.id,prev.number)}">← Episódio anterior</a>`:'<span></span>'}${next?`<a class="btn primary" href="${watchUrl(a.id,next.number)}">Próximo episódio →</a>`:'<a class="btn" href="anime.html?id='+encodeURIComponent(a.id)+'">Voltar ao anime</a>'}</div><h2>Lista de episódios</h2><div class="episodes">${sorted.map(e=>{const ready=Boolean((e.sourceUrl||"").trim());return `<div class="episode ${e.number===ep.number?"episode-current":""}"><b>${String(e.number).padStart(2,"0")}</b><div><strong>${esc(e.title)}</strong><small>${esc(e.duration||"Duração não informada")} · ${ready?"Fonte configurada":"Vídeo pendente"}</small></div><a class="btn ${e.number===ep.number?"":"primary"}" href="${watchUrl(a.id,e.number)}">${e.number===ep.number?"Atual":"Abrir"}</a></div>`}).join("")}</div><p class="notice">Use apenas vídeos que você criou, tem autorização para distribuir ou que tenham licença compatível. Não hospedamos nem fornecemos episódios protegidos por direitos autorais.</p></section>`;
  const video=document.querySelector("#episodeVideo"),playerNote=document.querySelector("#playerNote");
  if(video){video.addEventListener("error",()=>{playerNote.textContent="Não foi possível reproduzir o vídeo. Verifique a URL HTTPS, se o arquivo está público e se o servidor permite reprodução por outros sites (CORS)."});video.addEventListener("loadedmetadata",()=>{if(Number.isFinite(video.duration)&&video.duration>0)playerNote.textContent=`Vídeo carregado · ${Math.floor(video.duration/60)}:${String(Math.floor(video.duration%60)).padStart(2,"0")}`})}
}
init().catch(error=>{console.error(error);const root=document.querySelector("#content");if(root)root.innerHTML='<section class="section"><h1>Não foi possível carregar o player</h1><p class="muted">Confira sua conexão, config.js, login e catalog.json.</p><a class="btn primary" href="catalog.html">Voltar ao catálogo</a></section>'});
